name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux-i386:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-i386
      run: |
        scripts/build-ubuntu-i386.sh
        cd build/
        zip -r ../out.zip *
    - name: Upload linux-i386 artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-linux-i386.zip
        path: out.zip

  build-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh
        cd build/
        zip -r ../out.zip *
    - name: Upload linux-amd64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-linux-amd64.zip
        path: out.zip

  build-android-armv7a:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh

  build-windows-i386:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug --32bits
        ./waf.bat build
        cd build\
        tar -a -c -f ..\out.zip *.*
    - name: Upload win-i386 artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-win-i386.zip
        path: out.zip

  build-windows-amd64:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug
        ./waf.bat build
        cd build\
        tar -a -c -f ..\out.zip *.*
    - name: Upload win-amd64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-win-amd64.zip
        path: out.zip

  build-dedicated-windows-i386:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d
        ./waf.bat build
        cd build\
        tar -a -c -f ..\out.zip *.*
    - name: Upload win-i386 dedicated artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-win-i386-dedicated.zip
        path: out.zip

  build-dedicated-windows-amd64:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d
        ./waf.bat build
        cd build\
        tar -a -c -f ..\out.zip *.*
    - name: Upload win-amd64 dedicated artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-win-amd64-dedicated.zip
        path: out.zip

  build-dedicated-linux-i386:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-i386
      run: |
        scripts/build-ubuntu-i386.sh -d
        cd build/
        zip -r ../out.zip *
    - name: Upload linux-i386 dedicated artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-linux-i386-dedicated.zip
        path: out.zip

  build-dedicated-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh -d
        cd build/
        zip -r ../out.zip *
    - name: Upload linux-amd64 dedicated artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-linux-amd64-dedicated.zip
        path: out.zip

  build-macos-amd64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macos-amd64
      run: |
        scripts/build-macos-amd64.sh

  build-dedicated-macos-amd64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated macos-amd64
      run: |
        scripts/build-macos-amd64.sh -d
